# Generated by Django 4.2.7 on 2023-11-10 23:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0003_alter_dish_dish_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dishtype",
            options={"verbose_name": "Dish", "verbose_name_plural": "Dishes"},
        ),
    ]
