# Generated by Django 4.2.7 on 2023-11-10 23:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0004_alter_dishtype_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dish",
            options={"verbose_name": "Dish", "verbose_name_plural": "Dishes"},
        ),
        migrations.AlterModelOptions(
            name="dishtype",
            options={},
        ),
    ]
